# https://github.com/marketplace/actions/label-commenter

labels:
  - name: "integration: utility_meter"
    labeled:
      issue:
        body: "#HomeAssistant ```utility_meter``` integration documentation - https://www.home-assistant.io/integrations/utility_meter/"
